# Random Spell Component Material
# Component databased used from https://arcane.org/dd-5e-spell-component-database/
# Developer: Warren, https://www.patreon.com/rpgpython
# Script Version Number: v1.0
# Date: 21 March 2021

# If script errors, you may need to install the random package
# https://pypi.org/project/random2/
# pip install random2
# Installing packages: https://packaging.python.org/tutorials/installing-packages/
import random

components = random.choice([["0","Flaming Sphere","Bit of tallow"],
["0","Dancing Lights","Bit of Phosphorus"],
["0","Dancing Lights","Bit of Wytchwood"],
["0","Dancing Lights","Glowworm"],
["0","Friends","Small amount of makeup applied to face"],
["0","Light","Firefly"],
["0","Light","Phosphorescent moss"],
["0","Mending","Two lodestones"],
["0","Message","Short piece of copper wire"],
["0","Minor Illusion","Bit of fleece"],
["0","Resistance","Miniature cloak"],
["0","Shillelagh","Mistletoe"],
["0","Shillelagh","Shamrock leaf"],
["0","Shillelagh","Club or Quarterstaff"],
["0","Thorn Whip","Stem of plant with thorns"],
["0","Booming Blade","A weapon"],
["0","Green-Flame","A weapon"],
["0","Infestation","Living flea"],
["0","Word of Radiance","Holy Symbol"],
["1","Alarm","Tiny Bell"],
["1","Alarm","Piece of Fine Silver Wire"],
["1","Animal Friendship","Morsel of Food"],
["1","Armor of Agathys","Cup of Water"],
["1","Bane","Drop of Blood"],
["1","Bless","Sprinkling of Holy Water"],
["1","Chromatic Orb","Diamond - 50gp"],
["1","Color Spray","Pinch of Powder - Red"],
["1","Color Spray","Pinch of Powder - Yellow"],
["1","Color Spray","Pinch of Powder - Blue"],
["1","Color Spray","Pinch of Sand - Red"],
["1","Color Spray","Pinch of Sand - Yellow"],
["1","Color Spray","Pinch of Sand - Blue"],
["1","Comprehend Language","Pinch of Soot"],
["1","Comprehend Language","Pinch of Salt"],
["1","Create Water","Drop of Water"],
["1","Destroy Water","Grains of Sand"],
["1","Detect Poison and Disease","Yew Leaf"],
["1","Feather Fall","Small feather"],
["1","Feather Fall","Piece of down"],
["1","Find Familiar","10gp of Charcoal - Incense and Herbs"],
["1","Find Familiar","Brass Brazier"],
["1","Goodberry","Sprig of Mistletoe"],
["1","Grease","Bit of pork rind"],
["1","Grease","Butter"],
["1","Hex","Petrified Eye of Newt"],
["1","Identify","Pearl - 100gp"],
["1","Identify","Owl feather"],
["1","Illusory Script","Lead-based ink - 10gp"],
["1","Jump","Grasshopper's hind leg"],
["1","Longstrider","Pinch of dirt"],
["1","Mage Armor","Bit of cured leather"],
["1","Protection from Good and Evil","Holy Water"],
["1","Protection from Good and Evil","Powdered silver and iron"],
["1","Sanctuary","Small silver mirror"],
["1","Shield of Faith","Small parchment with holy text"],
["1","Silent Image","Bit of fleece"],
["1","Sleep","Pinch of fine sand"],
["1","Sleep","Rose petals"],
["1","Sleep","Cricket"],
["1","Tasha's Hideous Laughter","Tiny tarts"],
["1","Tasha's Hideous Laughter","Feather"],
["1","Tenser's Floating Disk","Drop of mercury"],
["1","Unseen Servant","Piece of string"],
["1","Unseen Servant","Bit of wood"],
["1","Witch Bolt","Twig from tree struck by lightning"],
["1","Beast Bond","Bit of fur wrapped in cloth"],
["1","Ceremony","Powdered silver - 25gp"],
["1","Ice Knife","Drop of water"],
["1","Ice Knife","Piece of ice"],
["1","Snare","25' rope"],
["2","Aid","Tiny Strip of White Cloth"],
["2","Animal Messenger","Morsel of Food"],
["2","Arcane Lock","Gold Dust - 25gp"],
["2","Augury","Specially Marked Sticks - 25gp"],
["2","Augury","Specially Marked Bones - 25gp"],
["2","Augury","Specially Marked Tokens - 25gp"],
["2","Barkskin","Handful of Oak Bark"],
["2","Cloud of Darkness","Sliver of Glass"],
["2","Continual Flame","Ruby Dust - 50gp"],
["2","Cordon of Arrows","Arrows"],
["2","Cordon of Arrows","Bolts"],
["2","Darkness","Bat Fur"],
["2","Darkness","Drop of Pitch"],
["2","Darkness","Piece of Coal"],
["2","Darkvision","Pinch of Dried Carrot"],
["2","Darkvision","Agate"],
["2","Detect Thoughts","Copper piece"],
["2","Enhance Ability","Fur of a beast"],
["2","Enhance Ability","Feather of a bird"],
["2","Enlarge","Pinch of Powdered Iron"],
["2","Reduce","Pinch of Powdered Iron"],
["2","Flame Blade","Leaf of sumac"],
["2","Flaming Sphere","Pinch of brimstone"],
["2","Flaming Sphere","Dusting of powdered iron"],
["2","Gentle Repose","Pinch of salt"],
["2","Gentle Repose","Copper coin (per eye)"],
["2","Gust of Wind","Legume seed"],
["2","Heat Metal","Piece of iron"],
["2","Heat Metal","Flame"],
["2","Hold Person","Small - straight piece of iron"],
["2","Invisibility","Eyelash encased in gum arabic"],
["2","Levitate","Small leather loop"],
["2","Levitate","Golden wire bent into a cup shape with a long shank on one end"],
["2","Locate Animals and Plants","Bit of fur from a bloodhound"],
["2","Locate Object","Forked Twig"],
["2","Magic Mouth","Bit of honeycomb"],
["2","Magic Mouth","Jade Dust - 10gp"],
["2","Melf's Acid Arrow","Powdered rhubarb leaf"],
["2","Melf's Acid Arrow","Adder's stomach"],
["2","Moonbeam","Several seeds of moonseed plant"],
["2","Moonbeam","Piece of opalescent feldspar"],
["2","Nystal's Magic Aura","Small square of silk"],
["2","Pass without Trace","Burned leaf of mistletoe"],
["2","Pass without Trace","Sprig of spruce"],
["2","Phantasmal Force","Bit of fleece"],
["2","Rope Trick","Powdered corn extract"],
["2","Rope Trick","Twisted loop of parchment"],
["2","See Invisibility","Pinch of talc"],
["2","See Invisibility","Small sprinkling powdered silver"],
["2","Shatter","Chip of mica"],
["2","Spider Climb","Drop of bitumen"],
["2","Spider Climb","Spider"],
["2","Spike Growth","Seven sharp thorns"],
["2","Spike Growth","Seven small sharpened twigs"],
["2","Suggestion","Snake's tongue"],
["2","Suggestion","Bit of honeycomb"],
["2","Suggestion","Drop of sweet oil"],
["2","Warding Bond","Pair of platinum rings - 50gp each"],
["2","Web","Bit of spiderweb"],
["2","Aganazzar's Scorcher","Red Dragon's scale"],
["2","Dragon's Breath","Hot pepper"],
["2","Dust Devil","Pinch of dust"],
["2","Maximillian's Earthen Grasp","Miniature hand sculpted from clay"],
["2","Snilloc's Snowball Swarm","Piece of ice"],
["2","Snilloc's Snowball Swarm","Small white rock chip"],
["3","Animate Dead","Drop of Blood"],
["3","Animate Dead","Piece of Flesh"],
["3","Animate Dead","Pinch of Bone Dust"],
["3","Clairvoyance","Jeweled Horn - 100gp"],
["3","Clairvoyance","Glass Eye - 100gp"],
["3","Conjure Barrage","Ammunition"],
["3","Conjure Barrage","Arrow"],
["3","Conjure Barrage","Bolt"],
["3","Conjure Barrage","Thrown Weapon"],
["3","Fear","White feather"],
["3","Fear","Heart of a hen"],
["3","Feign Death","Pinch of graveyard dust"],
["3","Fireball","Tiny ball of bat guano & sulfur"],
["3","Fly","Wing feather of any bird"],
["3","Gaseous Form","Bit of gauze"],
["3","Gaseous Form","Wisp of smoke"],
["3","Glyph of Warding","Incense & Powdered Diamond Dust - 200gp"],
["3","Haste","Shaving of licorice root"],
["3","Hunger of Hadar","Pickled octopus tentacle"],
["3","Hypnotic Pattern","Small glowing stick of incense"],
["3","Hypnotic Pattern","Crystal Vial of phosphorescent material"],
["3","Leomund's Tiny Hut","Small crystal bead"],
["3","Lightning Bolt","Bit of Fur"],
["3","Lightning Bolt","Rod of amber"],
["3","Lightning Bolt","Rod of crystal"],
["3","Lightning Bolt","Rod of glass"],
["3","Magic Circle","Holy Water"],
["3","Magic Circle","Powdered Silver and Iron - 100gp"],
["3","Major Image","Bit of fleece"],
["3","Non-Detection","Pinch of diamond dust - 25gp"],
["3","Revivify","Diamonds - 300gp"],
["3","Sending","Short piece of fine copper wire"],
["3","Sleet Storm","Pinch of dust"],
["3","Sleet Storm","Few drops of water"],
["3","Slow","Drop of molasses"],
["3","Speak with Dead","Burning Incense"],
["3","Spirit Guardians","Holy Symbol"],
["3","Stinking Cloud","Rotten egg"],
["3","Stinking Cloud","Several skunk cabbage leaves"],
["3","Tongues","Small clay model of ziggurat"],
["3","Water Breathing","Short reed"],
["3","Water Breathing","Piece of straw"],
["3","Water Walk","Piece of cork"],
["3","Wind Wall","Tiny fan"],
["3","Wind Wall","Feather of exotic origin"],
["3","Catnap","Pinch of sand"],
["3","Erupting Earth","Piece of Obsidian"],
["3","Melf's Minute Meteors","Niter - sulfur and pine tar formed into a bead"],
["3","Summon Lesser Demons","Vial of blood from humanoid killed in last 24 hours"],
["3","Tidal Wave","Drop of water"],
["3","Wall of Sand","Handful of sand"],
["3","Wall of Water","Drop of water"],
["4","Arcane Eye","Bit of Bat Fur"],
["4","Banishment","Distasteful Item"],
["4","Confusion","Nutshells - 3"],
["4","Conjure Woodland Being","Holly Berry"],
["4","Control Water","Drop of Water"],
["4","Control Water","Pinch of Dust"],
["4","Divination","Incense"],
["4","Divination","Sacrificial Offering - 25gp"],
["4","Evard's Black Tentacles","Piece of tentacle from giant octopus"],
["4","Evard's Black Tentacles","Piece of tentacle from giant squid"],
["4","Fire Shield","Bit of Phosphorus"],
["4","Fire Shield","Firefly"],
["4","Freedom of Movement","Leather strap - bound around arm-limb"],
["4","Hallucinatory Terrain","A stone"],
["4","Hallucinatory Terrain","A twig"],
["4","Hallucinatory Terrain","Bit of green plant"],
["4","Ice Storm","Pinch of dust"],
["4","Ice Storm","Few drops of water"],
["4","Leomund's Secret Chest","Chest - 5000gp"],
["4","Leomund's Secret Chest","Tiny Chest - 50gp"],
["4","Locate Creature","Bit of fur from a bloodhound"],
["4","Mordenkainen's Faithful Hound","Tiny silver whistle"],
["4","Mordenkainen's Faithful Hound","Piece of bone"],
["4","Mordenkainen's Faithful Hound","Thread"],
["4","Mordenkainen's Private Sanctum","Thin sheet of lead"],
["4","Mordenkainen's Private Sanctum","Piece of opaque glass"],
["4","Mordenkainen's Private Sanctum","Wad of cotton"],
["4","Mordenkainen's Private Sanctum","Wad of cloth"],
["4","Mordenkainen's Private Sanctum","Powdered chrysolite"],
["4","Otiluke's Resilient Sphere","Hemispherical sphere of clear crystal"],
["4","Otiluke's Resilient Sphere","Hemispherical sphere of gum arabic"],
["4","Polymorph","Caterpillar cocoon"],
["4","Stone Shape","Soft Clay"],
["4","Stoneskin","Diamond Dust - 100gp"],
["4","Wall of Fire","Small piece of phosphorus"],
["4","Shadow of Moil","Undead eyeball encased in gem - 150gp"],
["4","Summon Greater Demon","Vial of blood from humanoid killed in last 24 hours"],
["4","Vitriolic Sphere","Drop of giant slug bile"],
["4","Watery Sphere","Droplet of water"],
["5","Awaken","Agate - 1000gp"],
["5","Bigby's Hand","Eggshell"],
["5","Bigby's Hand","Snakeskin Glove"],
["5","Commune","Incense"],
["5","Commune","Vial of Holy Water"],
["5","Commune","Vial of Unholy Water"],
["5","Cone of Cold","Small Crystal Cone"],
["5","Cone of Cold","Small Glass Cone"],
["5","Conjure Elemental","Burning Incense"],
["5","Conjure Elemental","Soft Clay"],
["5","Conjure Elemental","Sulfur"],
["5","Conjure Elemental","Phosphorus"],
["5","Conjure Elemental","Water"],
["5","Conjure Elemental","Sand"],
["5","Conjure Volley","Ammunition"],
["5","Conjure Volley","Arrow"],
["5","Conjure Volley","Bolt"],
["5","Conjure Volley","Thrown Weapon"],
["5","Creation","Tiny Piece of Matter (of type created)"],
["5","Dispel Evil and Good","Holy Water"],
["5","Dispel Evil and Good","Powdered Silver"],
["5","Dispel Evil and Good","Powdered Iron"],
["5","Dream","Handful of sand"],
["5","Dream","Dab of ink"],
["5","Dream","Writing Quill plucked from sleeping bird"],
["5","Flame Strike","Pinch of sulfur"],
["5","Greater Restoration","Diamond Dust - 100gp"],
["5","Hallow","Herbs - Oils & Incense - 1000gp"],
["5","Hold Monster","Small - straight piece of iron"],
["5","Insect Plague","Few grains of sugar"],
["5","Insect Plague","Some kernels of grain"],
["5","Insect Plague","Smear of fat"],
["5","Legend Lore","Incense - 250gp"],
["5","Legend Lore","Ivory strip - 50gp"],
["5","Legend Lore","Ivory strip - 50gp"],
["5","Legend Lore","Ivory strip - 50gp"],
["5","Legend Lore","Ivory strip - 50gp"],
["5","Passwall","Pinch of sesame seeds"],
["5","Planar Binding","Jewel - 1000gp"],
["5","Raise Dead","Diamond - 500gp"],
["5","Rary's Telepathic Bond","Piece of eggshell (two types)"],
["5","Reincarnate","Rare oils and ungents - 1000gp"],
["5","Scrying","Crystal ball - silver mirror - font of holy water; 1000gp"],
["5","Swift Quiver","Quiver with at least one piece of ammo"],
["5","Teleportation Circle","Rare chalks and inks infused with gems - 50gp"],
["5","Wall of Force","Pinch of powder from clear gemstone"],
["5","Wall of Stone","Small block of granite"],
["5","Dawn","Sunburst pendant - 100gp"],
["5","Infernal Calling","Ruby - 999gp"],
["5","Maelstrom","Paper or Leaf in shape of a funnel"],
["5","Negative Energy Flood","Broken bone"],
["5","Negative Energy Flood","Square of black silk"],
["5","Steel Wind Strike","Melee weapon - 1sp"],
["5","Transmute Rock","Clay"],
["5","Transmute Rock","Water"],
["5","Wall of Light","Hand mirror"],
["6","Chain Lightning","Bit of Fur"],
["6","Chain Lightning","Piece of Amber"],
["6","Chain Lightning","Piece of Glass"],
["6","Chain Lightning","Crystal Rod"],
["6","Chain Lightning","Silver Pin"],
["6","Circle of Death","Powder of Crushed Black Pearl - 500gp"],
["6","Contingency","Statuette of Self Ivory Gems - 1500gp"],
["6","Create Undead","Clay Pot filled with Grave Dirt"],
["6","Create Undead","Clay Pot filled with Brackish Water"],
["6","Create Undead","Black Onyx - 150gp"],
["6","Disintegrate","Lodestone"],
["6","Disintegrate","Pinch of dust"],
["6","Drawmij's Instant Summons","Sapphire - 1000gp"],
["6","Find the Path","Divinatory Tools: Bone - 100gp"],
["6","Find the Path","Divinatory Tools: Ivory Sticks - 100gp"],
["6","Find the Path","Divinatory Tools: Cards - 100gp"],
["6","Find the Path","Divinatory Tools: Teeth - 100gp"],
["6","Find the Path","Divinatory Tools: Carved Runes - 100gp"],
["6","Find the Path","Object from location"],
["6","Flesh to Stone","Pinch of lime - water - and earth"],
["6","Forbiddance","Sprinkling of Holy Water"],
["6","Forbiddance","Rare incense"],
["6","Forbiddance","Powdered Ruby - 1000gp"],
["6","Globe of Invulnerability","Glass bead"],
["6","Globe of Invulnerability","Crystal bead"],
["6","Guards and Wards","Burning Incense"],
["6","Guards and Wards","Small measure of brimstone"],
["6","Guards and Wards","Small measure of oil"],
["6","Guards and Wards","Knotted string"],
["6","Guards and Wards","Small amount of umber hulk blood"],
["6","Guards and Wards","Small silver rod - 10gp"],
["6","Heroes' Feast","Gem-Encrusted Bowl - 1000gp"],
["6","Magic Jar","Gem - Crystal - Reliquary or Container - 500gp"],
["6","Mass Suggestion","Snake's tongue"],
["6","Mass Suggestion","Bit of honeycomb"],
["6","Mass Suggestion","Drop of sweet oil"],
["6","Move Earth","Iron blade"],
["6","Move Earth","Small bag of clay - loam and sand"],
["6","Otiluke's Freezing Sphere","Small crystal sphere"],
["6","Programmed Illusion","Bit of fleece"],
["6","Programmed Illusion","Jade Dust - 25gp"],
["6","Sunbeam","Magnifying glass"],
["6","True Seeing","Ointment for eyes (mushroom powder - saffron - fat) - 25gp"],
["6","Wall of Ice","Small piece of quartz"],
["6","Wall of Thorns","Handful of thorns"],
["6","Wind Walk","Fire"],
["6","Wind Walk","Holy Water"],
["6","Create Homunculus","Clay"],
["6","Create Homunculus","Ash"],
["6","Create Homunculus","Mandrake root"],
["6","Create Homunculus","Jewel-encrusted dagger - 1000GP"],
["6","Druid Grove","Mistletoe - harvested with golden sickle under light of full moon"],
["6","Soul Cage","Tiny silver cage - 100gp"],
["6","Tenser's Transformation","Few hairs from a bull"],
["7","Delayed Blast Fireball","Tiny ball of bat guano & sulfur"],
["7","Forcecage","Ruby Dust - 1500gp"],
["7","Mordenkainen's Magnificent Mansion","Miniature portal carved from ivory - 5gp"],
["7","Mordenkainen's Magnificent Mansion","Small piece of polished marble - 5gp"],
["7","Mordenkainen's Magnificent Mansion","Tiny silver spoon - 5gp"],
["7","Mordenkainen's Sword","Miniature platinum sword - grip and pommel of copper and zinc - 250gp"],
["7","Planar Shift","Forked - metal rod - 250gp (per Plane)"],
["7","Project Illusion","Small replica of caster - 5gp"],
["7","Regenerate","Prayer wheel"],
["7","Regenerate","Holy Water"],
["7","Resurrection","Diamond - 1000gp"],
["7","Reverse Gravity","Lodestone"],
["7","Reverse Gravity","Iron fillings"],
["7","Sequester","Powdered diamond - emerald - ruby - and sapphire; 5000gp"],
["7","Simulacrum","Snow-ice to creature size"],
["7","Simulacrum","Fingernail - hair or body parts of creature"],
["7","Simulacrum","Powdered Ruby - 1500gp"],
["7","Symbol","Mercury - phosphorus - powdered diamond and opal; 1000gp"],
["7","Temple of the Gods","Holy Symbol - 5gp"],
["7","Whirlwind","Piece of straw"],
["8","Antimagic Field","Pinch of Powdered Iron"],
["8","Antimagic Field","Iron Filings"],
["8","Antipathy","Lump of Alum Soaked in Vinegar"],
["8","Sympathy","Drop of Honey"],
["8","Clone","Diamond - 1000gp"],
["8","Clone","Cubic Inch of Flesh"],
["8","Clone","Vessel - 2000gp"],
["8","Clone","Salt Water"],
["8","Control Weather","Burning Incense"],
["8","Control Weather","Bits of Earth & Wood mixed in Water"],
["8","Earthquake","Pinch of dirt"],
["8","Earthquake","Piece of rock"],
["8","Earthquake","Lump of clay"],
["8","Feeblemind","Handful of clay"],
["8","Feeblemind","Handful of crystal"],
["8","Feeblemind","Handful of glass"],
["8","Feeblemind","Handful of minerals spheres"],
["8","Holy Aura","Tiny Reliquary - 1000gp"],
["8","Sunburst","Fire"],
["8","Sunburst","Piece of sunstone"],
["8","Telepathy","Pair of linked silver rings"],
["8","Abi-Dalzim's Horrid Wilting","Bit of sponge"],
["8","Maddening Darkness","Drop of pitch mixed with Drop of mercury"],
["8","Mighty Fortress","Diamond - 500gp"],
["9","Astral Projection","Jacinth - 1000gp"],
["9","Astral Projection","Ornately Carved Silver Bar - 100gp"],
["9","Foresight","Hummingbird feather"],
["9","Gate","Diamond - 5000gp"],
["9","Imprisonment","Vellum Depiction"],
["9","Imprisonment","Carved Statuette"],
["9","Shapechange","Jade Circlet - 1500gp"],
["9","True Polymorph","Drop of mercury"],
["9","True Polymorph","Dollop of gum arabic"],
["9","True Polymorph","Wisp of smoke"],
["9","True Resurrection","Sprinkling of Holy Water"],
["9","True Resurrection","Diamonds - 25000GP"],
["9","Invulnerability","Small piece of adamnatine - 500gp"],
["9","Mass Polymorph","Caterpillar cocoon"]])

print("\nComponent: " + components[2])
print("Spell: " + components[1])
print("Spell Level: " + components[0])
print("\n")